Calender
rosh-1228/ruby-practices pull request #3
Opened 2021-03-17 14:31 UTC by rosh-1228

カレンダープログラムを提出します。
    -mオプション
        [引数]
            指定した1〜12の数値のカレンダーを表示
    -yオプション
        [引数]
            指定した0〜9999の数値のカレンダーを表示

2021-03-22 07:24 UTC, u1tnk requested changes
全体的な指摘があったので目につくところだけコメントしています。
全体の指摘は以下です。

- rubocopが通っていません。 https://bootcamp.fjord.jp/practices/142 これは毎回書いていませんが、このプラクティス通り常に通すようにしてください。
- コメントが多いですね。 「show_calendar」で「カレンダーを表示」のように変数やメソッドで見て分かるものは不要です。できるだけコメント無しで理解できるプログラムを目指しましょう。
-  空行がまったく無いです。意味のまとまりで分かりやすくなるように適切に空けましょう。

2021-03-22 07:24 UTC, u1tnk commented on 02.calendar/cal.rb
> +      print(adjust_space(5))
基本的に3文字間隔ですが、最初だけ5なのは意図的でしょうか？
ちなみに全部3文字間隔ならこのようにせずに計算で出す事ができます。曜日が数値で取得可能なのがヒントです。

2021-03-22 07:24 UTC, u1tnk commented on 02.calendar/cal.rb
> +# オプション存在チェック
ここはもっと簡潔に書けますね。

yとmそれぞれで処理して両方初期値を入れてしまえば途中でexit書く事も無いですね。
あとは書いても問題は無いですが、仕事じゃないので validation errorのときのメッセージまでしっかり書かなくても大丈夫です 🙆‍♀️

2021-03-22 07:24 UTC, u1tnk commented on 02.calendar/cal.rb
> +    options.delete(:m)
特に放置しても問題無いので deleteしなくても良いと思います。

2021-03-22 07:24 UTC, u1tnk commented on 02.calendar/cal.rb
> +  unless options[:y] =~ /\A[-+]?[0-9]*\.?[0-9]+\Z/ then
こちらもおかしくは無いのですが、 `Integer('0.1')` 等 rubyの機能を使って有効か判定するぐらいで大丈夫です 🙆‍♀️

2021-03-22 07:24 UTC, u1tnk commented on 02.calendar/cal.rb
> +  CALENDER_WEEK = ["日","月","火","水","木","金","土"]
こういうのはrubyでは `%(1 2 3)` のように %記法で書くとすっきりしますよ。

2021-03-29 15:13 UTC, rosh-1228 commented on 02.calendar/cal.rb
> +      print(adjust_space(5))
place_first_dayメソッドは、月初日の表示位置を調整するために作成しました。
最初の5は、月初日(◯月1日)が月曜日の場合は、半角5文字目に1日を表示させたく5としました。
例えば、以下の画像のように月曜日の列に1日を表示させたい時は、.rjust(5)でスペースを調整しています。
![-bash](https://user-images.githubusercontent.com/64620506/112332230-e9609400-8cfc-11eb-82da-7e38ad770dba.png)
月初日(1日)が火曜日の場合は、.rjust(8)と曜日が1つずれるにつれて+3しています。
日曜日の場合だけは、rjust(0)で以下のように表示されるので、print(adjust_space(0))としております。
![-bash](https://user-images.githubusercontent.com/64620506/112332742-5c6a0a80-8cfd-11eb-836f-39f3748a9967.png)
すみません、ご質問の意図に沿って回答できているでしょうか？💦💦

2021-03-29 15:14 UTC, rosh-1228 commented on 02.calendar/cal.rb
> +# オプション存在チェック
ご指摘ありがとうございます。
getoptsで初期値を指定して、exitを無くしました😄

validation errorもいったんメッセージを無くしました。

2021-03-29 15:15 UTC, rosh-1228 commented on 02.calendar/cal.rb
> +    options.delete(:m)
ご指摘ありがとうございます。
deleteの箇所を削除して、修正しました😄

2021-03-29 15:16 UTC, rosh-1228 commented on 02.calendar/cal.rb
> +  CALENDER_WEEK = ["日","月","火","水","木","金","土"]
なるほど！
%記法を完全に失念しておりました😓
修正しました！
もう一度復習して、次回以降使えるようにします！

2021-03-29 15:20 UTC, rosh-1228 commented
> rubocopが通っていません。 https://bootcamp.fjord.jp/practices/142 これは毎回書いていませんが、このプラクティス通り常に通すようにしてください。
rubocopを通しました！
すみません。プラクティスが先のほうでしたので、一旦無しで提出してしまいました😓
ご指摘いただいて、勉強になりました！
以後通すようにします😁

> コメントが多いですね。 「show_calendar」で「カレンダーを表示」のように変数やメソッドで見て分かるものは不要です。できるだけコメント無しで理解できるプログラムを目指しましょう。
ありがとうございます！
コメント無しでもわかるような命名を心がけてプログラムを作成していくようにします！
一旦不要だと思ったコメントは全て削除しました。

>空行がまったく無いです。意味のまとまりで分かりやすくなるように適切に空けましょう。
空行も作りました！

2021-03-30 03:45 UTC, u1tnk commented on 02.calendar/cal.rb
> +      print(adjust_space(5))
はい、意図通りの回答です。
なんですが、最初の日曜の初期値がズレるのはともかくあとは3文字ずつの間隔に見えるのでおかしいなあと思っています。日曜日って rjust(2)で良かったりしません？

2021-03-30 05:15 UTC, u1tnk requested changes

2021-03-30 05:15 UTC, u1tnk commented on 02.calendar/cal.rb
> +    if cal_day == @start_day_num
`cal_day == @start_day_num` が3回出てきています。
```
if cal_day == @start_day_num
  if xxx
  else
  end
elseif get_day...
end
```

のようにネストさせれば重複が減らせると思います。
また 、putsはかっこを付けず、printはかっこを付けてるようですが、同じメソッドなので統一した方が良いですね。
プロジェクトでも変わりますが、個人的に基本は付けないが、複雑になったりしたときだけ付けるようにしています。

2021-03-30 05:15 UTC, u1tnk commented on 02.calendar/cal.rb
> +  def self.place_first_day
計算で出せればなお良いですが、このぐらい簡潔ならこれでも良いですね。
あと、こういう分岐だとcase/whenの方が一般的な気はします。

2021-03-30 14:39 UTC, rosh-1228 commented on 02.calendar/cal.rb
> +      print(adjust_space(5))
ありがとうございます！
3文字間隔の規則でいくとrjust(2)で良いですね💦

2021-03-30 14:43 UTC, rosh-1228 commented on 02.calendar/cal.rb
> +    if cal_day == @start_day_num
`cal_day == @start_day_num `が1つと`cal_day == @end_day_num`が2つですね😃
確かにネストすると、`cal_day == @end_day_num`が1回だけで済みますね！
また、複雑なりそうでしたので、メソッドに分けました！

2021-03-30 14:45 UTC, rosh-1228 commented on 02.calendar/cal.rb
> +  def self.place_first_day
case/whenが一般的なんですね💦
以降、elsifが多くなったら意識してcase文を意識して書くようにします！

2021-03-31 06:20 UTC, u1tnk commented on 02.calendar/cal.rb
> +  def self.place_first_day
ここまでやったら計算で出せると一行になるのでやってみましょう！ `@start_day.wday` で数値になるのがヒントです！

2021-03-31 06:21 UTC, u1tnk commented on 02.calendar/cal.rb
> +  def self.day_is_sunday?(cal_year, cal_month, cal_day)
細かいのですが rubyは ?を付ける習慣があるので is_ はほぼ使いません。内容からして メソッド名は `sunday?`で良さそうかと。

2021-03-31 20:58 UTC, rosh-1228 commented on 02.calendar/cal.rb
> +  def self.place_first_day
wdayで数値化して曜日ごとに月初日を表示するように修正できました！😄
計算して表示させるということになんで今まで気づかなかったのか？という疑問だけがずっと出てくるくらい、シンプルに解決できました🤣
土曜日の場合だけ、putsしたいので、三項演算子を使って1行にしました！

2021-03-31 20:59 UTC, rosh-1228 commented on 02.calendar/cal.rb
> +  def self.day_is_sunday?(cal_year, cal_month, cal_day)
ありがとうございます！
isは使わず?だけで表現する習慣なのですね！
修正しました！

2021-04-04 04:39 UTC, merged